game = "the-sprawl"
gameDefinition = "the-sprawl"
playbookKind = "the-sprawl-playbook"
playbook = "le-veilleur"
moves = ["evaluer-la-zone"]
mcMoves = ["fermer-la-nasse"]
variants = ["base"]
defaultVariant = "base"
