game = "urban-shadows"
gameDefinition = "urban-shadows"
playbookKind = "urban-shadows-playbook"
playbook = "the-aware"
moves = ["read-the-current"]
mcMoves = ["tighten-the-web"]
variants = ["base"]
defaultVariant = "base"
