game = "monsterhearts"
gameDefinition = "monsterhearts"
playbookKind = "monsterhearts-playbook"
playbook = "la-selkie"
moves = []
mcMoves = []
variants = ["base", "drowned-lake"]
defaultVariant = "base"
