slug = "the-aware"
name = "The Aware"
game = "urban-shadows"
description = "A mortal who has learned the city has monsters."
stats = { blood = 0, heart = 1, mind = -1, spirit = 1 }
moves = []
endMove = "Entrust your mortal relationships to another character."
